# configs/dataset/csv_spec.yaml
name: csvspec

# CSV 경로 (필수)
train_csv: "/home/user/Spectral_Data/QM_stratified_train_resplit_with_mu_eps.csv" # train_good_rows.csv QM_stratified_train_resplit_with_mu_eps, EM_stratified_train_clustered_resplit_with_mu_eps_fillZero
val_csv:   "" # D:/data/val.csv
test_csv:  "/home/user/Spectral_Data/QM_stratified_test_resplit_with_mu_eps.csv" # test_good_rows.csv QM_stratified_test_resplit_with_mu_eps ,  EM_stratified_test_clustered_resplit_with_mu_eps_fillZero.csv

# 컬럼/스펙트럼 범위 (당신의 CSV에 맞게)
smiles_col: SMILES         # SMILES가 없고 InChI만 있으면 null로 두세요
inchi_col: InChI           # InChI 없으면 null
spectrum_start: 200
spectrum_end: 800

# 전역 조건 컬럼들 (csv_spectrum_dataset.py가 사용)
global_cols: ["pH_label","dielectric_constant_avg","is_qm", "type"] # "solvent_phase"


# 옵션
spectrum_fill_eps: 1.0e-8
# fixed_vocabs: {pH_label: ["neutral", "basic", "acidic"], type: ["EM","AB"]}          # 필요시 {열이름: [v1,v2,...]} 로 명시 가능
fixed_vocabs:
  pH_label: ["neutral", "basic", "acidic"]
  type: ["EM", "AB"]


boolean_cols: ["is_qm"]
numeric_cols: ["dielectric_constant_avg"]   # (원래 자동 감지되면 생략 가능)
categorical_cols: ["pH_label", "type"] # "solvent_phase", "type"
remove_h: true           # RDKit에서 H 제거 여부
add_h: false              # H 추가하여 그래프화할지 여부
