general:
  name: spectrum_regression
  gpus: 1          # 0|1|auto|[0,1]
  check_val_every_n_epochs: 1
  test_only: null
  gpu_monitor: false
  gpu_monitor_interval: 50

trainer:
  precision: "16-mixed" # "16-mixed" "32-true"

train:
  accelerator: gpu
  devices: 2            # GPU 2장 사용. 전부면 -1
  strategy: ddp         # 또는 ddp_find_unused_false
  num_nodes: 1
  precision: 32 # 원하면 16-mixed

  #############
  n_epochs: 500
  batch_size: 256
  lr: 2e-4
  num_workers: 0
  save_model: true
  clip_grad: 1.0
  clip_algo: "norm"

  # 멀티로스 + GradNorm 옵션
  losses: ["MSE"]      # ["MSE","MAE","SOFTDTW","SID"] 등
  use_gradnorm: true
  alpha: 0.12
  softdtw_gamma: 0.2

  # 선택 기본값
  optimizer: adamw
  weight_decay: 1e-12
  seed: 0
  progress_bar: false
  ema_decay: 0
  milestones_metrics: [500]     # ← 이 에폭에 "지표 저장" 실행
  milestones_plots:   [500]        # ← 이 에폭에 "그림 저장"도 함께 실행
  milestone_n_samples: 32       # plot_all=false일 때 저장할 개수
  milestone_plot_all: true     # true면 해당 split 전체 저장
  milestone_eval_test: true    # true면 test도 함께 평가/저장

dataset:
  name: csvspec
  train_csv: "C:/Users/kogun/PycharmProjects/DiGress/data/csv/EM_stratified_train_clustered_resplit_with_mu_eps_fillZero.csv"
  val_csv: ""    # 빈 문자열 => train에서 90/10 split
  test_csv:  "C:/Users/kogun/PycharmProjects/DiGress/data/csv/EM_stratified_test_clustered_resplit_with_mu_eps_fillZero.csv"
  spec_start: 200
  spec_end: 800
  solvent_vocab: ["solid","liquid","gas"]
  ph_vocab: ["acidic","basic","neutral"]
  smiles_col: SMILES     # CSV에 SMILES 컬럼이 있으면
  inchi_col: InChI       # InChI 컬럼명
  add_h: false

model:
  backend: gnn         # gnn | digress
  hidden: 256
  layers: 4 # 4
  dropout: 0.1
  n_head: 8           # digress에서만 사용

hydra:
  run:
    dir: ./outputs_spectrum/${general.name}/${now:%Y%m%d_%H%M%S}
  job:
    chdir: true         # run.dir로 작업 폴더 이동(기본)
  output_subdir: null   # 불필요한 config 복사 폴더 방지(선택)




