general:
  name: spectrum_regression
  gpus: 1          # 0|1|auto|[0,1]
  check_val_every_n_epochs: 1
  test_only: null
  gpu_monitor: false
  gpu_monitor_interval: 50

trainer:
  precision: "32-true"

train:
  n_epochs: 500
  lr: 2e-4
  clip_grad: 0.0
  batch_size: 64
  num_workers: 0
  save_model: true

dataset:
  name: csvspec
  train_csv: "C:/Users/kogun/PycharmProjects/DiGress/data/csv/EM_stratified_train_clustered_resplit_with_mu_eps.csv"
  val_csv: ""    # 빈 문자열 => train에서 90/10 split
  test_csv:  "C:/Users/kogun/PycharmProjects/DiGress/data/csv/EM_stratified_test_clustered_resplit_with_mu_eps.csv"
  spec_start: 200
  spec_end: 800
  solvent_vocab: ["solid","liquid","gas"]
  ph_vocab: ["acidic","basic","neutral"]

model:
  hidden: 512
  layers: 12
  dropout: 0.1

hydra:
  run:
    dir: ./outputs_spectrum/${general.name}/${now:%Y%m%d_%H%M%S}
  job:
    chdir: true         # run.dir로 작업 폴더 이동(기본)
  output_subdir: null   # 불필요한 config 복사 폴더 방지(선택)




