defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : csv_spec

monitor:
  gpu_interval: 0        # 0 이면 끔, N이면 N step마다 출력
  rank_zero_only: false
  use_nvml: false

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}




